Repository ArkEcosystem/pay, pull requests merged in 2019-07, with the labels that each got.

#21 fix: interval not being cleared
  lib/index.js
Labels: Bounty: Tier 4, Complexity: Low, Status: Contributor Approved, Type: Bugfix

#23 chore(deps): update all dependencies to their latest versions
  .circleci/config.yml
  build/webpack.config.js
  jest.config.js
  lib/index.js
  package.json
  yarn.lock
Labels: Complexity: Undetermined, Status: In Progress, Type: Task

#26 chore: setup probot/stale configuration
  .github/stale.yml
Labels: Complexity: Low, Type: Task

#27 chore(readme): add lead maintainer information
  README.md
Labels: Complexity: Low, Type: Task
